-- TODO add some users, reviews, orders, order_items, perhars more products
INSERT INTO products (product_name, weight, height, length, diet, region, dino_type, description, image, stock, amount_sold, price, published) VALUES
(
    'aardonyx',
    1700,
    2,
    8.0,
    'herbivore',
    'south africa',
    'terrestrial',
    $$Aardonyx (Afrikaans aard, \\\"earth\\\" + Greek onux, \\\"nail, claw\\\") is a genus of basal sauropodomorph dinosaur. It is known from the type species Aardonyx celestae found from the Early Jurassic Elliot Formation of South Africa. A. celestae was named after Celeste Yates, who prepared much of the first known fossil material of the species. It has arm features that are intermediate between prosauropods and sauropods. Based on the structure of the hind limbs and pelvic girdle of Aardonyx, the dinosaur normally moved bipedally but could drop to quadrupedal movement similar to Iguanodon. It shares some attributes with giant quadrupedal sauropods like Apatosaurus.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/aardonyx.jpg',
    5,
    10,
    150.0,
    true
),
(
    'abelisaurus',
    3000,
    2,
    7.4,
    'carnivore',
    'south america',
    'terrestrial',
    $$The large theropod Abelisaurus comahuensis was similar to Albertosaurus from Alberta, Canada especially in it's size and lifestyle. It was a bipedal carnivore that probably reached 7 to 9 meters (25 to 30 feet) in length, although it is known from only one partial skull. But it's skull led two Argentinian paleontologists to put it in it's own family now known as the Abelisaurida. It lived in Argentina during the Late Cretaceous, 70 to 66 million years ago. Coining the type species Abelisaurus comahuensis, both genus and species were named and described by Argentine paleontologists José Bonaparte and Fernando Emilio Novas in 1985. The generic name recognizes Roberto Abel as the discoverer of the type specimen, and also as the former director of the provincial Museum of Cipolletti in Argentina, where the specimen is housed. It also incorporates the Greek σαυρος ("sauros"), meaning "lizard". The specific name comahuensis honors the Comahue region of Argentina, where the fossil was found.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/abelisaurus.jpg',
    3,
    5,
    200.0,
    false
),
(
    'abrictosaurus',
    3,
    0.35,
    1.2,
    'omnivore',
    'south africa',
    'terrestrial',
    $$This dinosaur is known from the fossil remains of only two individuals, found in the Upper Elliot Formation of Qacha's Nek District in Lesotho and Cape Province in South Africa. Heterodontosaurids like Abrictosaurus were small, early ornithischians, named for their markedly heterodont dentition. They are best known for the large, canine-like tusks (often called caniniforms) in both upper and lower jaws. There were no teeth in the front of the jaws, where a hard beak was used to crop vegetation. There were three premaxillary teeth, with the first two small and conical and the third enlarged to form the upper caniniform, counterpart to the even larger lower caniniform, which was the first dentary tooth. In the upper jaw, a large gap (or diastema) accommodated the lower caniniform tooth and separated the premaxillary teeth from the wider chewing teeth of the maxilla. Similar teeth lined the remainder of the lower jaw. Abrictosaurus is usually considered the most basal member of the family Heterodontosauridae.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/abrictosaurus.jpg',
    2,
    3,
    100.0,
    true
),
(
    'abrosaurus',
    4500,
    3.2,
    9.1,
    'herbivore',
    'asia',
    'terrestrial',
    $$Abrosaurus was discovered in 1984 by Ouyang Hui. Hui first named his find in his 1986 thesis as A. gigantorhinus, or Abrosaurus Gigantorhinus. It's classification has gone under many changes since. The fossils that were found are extremely fragmented, and scientists are still unsure whether this is a separate genus or not. Like most sauropods, Abrosaurus was a quadrupedal herbivore but it was rather small for a sauropod, not much more than 30 feet (9 m) long. Its head was boxy and topped with a tall bony arch containing the nostrils.The generic name meaning "delicate lizard (from from the Greek αβρος meaning "delicate" or "dainty" and σαυρος meaning "lizard")", refers to the nature of the skull, with large openings separated by thin bony struts. The only named species is now known as A. dongpoi, and is named after eleventh century Chinese poet Su Shi, also known as Su Dongpo, who was born in Sichuan.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/abrosaurus.jpg',
    5,
    2,
    250.0,
    true
),
(
    'abydosaurus',
    18000,
    5.48,
    18.3,
    'herbivore',
    'north america',
    'terrestrial',
    $$Abydosaurus was a moderately-sized sauropod dinosaur, a little smaller than Camarasaurus.  It had a high, boxy skull with a protruding snout – perfect for cropping vegetation from the tops of trees. Abydosaurus belongs to the same sauropod group as Camarasaurus, but it is most closely related to another Late Jurassic dinosaur from the Morrison Formation that you might have heard of – Brachiosaurus.  Although their skulls and neck bones are very similar, Abydosaurus had narrower teeth than Brachiosaurus. This allowed it to pack more teeth in its mouth and replace them at a faster rate as they wore out.  Like all dinosaurs and other reptiles, Abydosaurus replaced its teeth many times throughout its life.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/abydosaurus.jpg',
    2,
    1,
    300.0,
    true
),
(
    'acanthopholis',
    380,
    1.8,
    5.5,
    'herbivore',
    'europe',
    'terrestrial',
    $$Acanthopholis (/ˌækənˈθɒfoʊlɪs/; meaning \"spiny scales\") is a genus of ankylosaurian dinosaur in the family Nodosauridae that lived during the Late Cretaceous Period of England. The armour of Acanthopholis consisted of oval keeled plates set almost horizontally into the skin, with long spikes protruding from the neck and shoulder area, along the spine. Acanthopholis was quadrupedal and herbivorous. Its size has been estimated to be in the range of 3 to 5.5 meters (9.8 to 18.0 ft) long and approximately 380 kilograms (840 lb) in weight.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/acanthopholis.jpg',
    4,
    2,
    120.0,
    true  
),
(
    'achelousaurus',
    3000,
    2.5,
    6.0,
    'herbivore',
    'north america',
    'terrestrial',
    $$Achelousaurus is a genus of centrosaurine ceratopsid dinosaur that lived during the Late Cretaceous Period of what is now North America, about 74.2 million years ago. The first fossils of Achelousaurus were collected in Montana in 1987, by a team led by Jack Horner, with more finds made in 1989. In 1994, Achelousaurus horneri was described and named by Scott D. Sampson; the generic name means \"Achelous lizard\", in reference to the Greek deity Achelous, and the specific name refers to Horner. The genus is known from a few specimens consisting mainly of skull material from individuals, ranging from juveniles to adults. A large centrosaurine, Achelousaurus supposedly was about 6 m (20 ft) long, with a weight of about 3 t (3.3 short tons). As a ceratopsian, it walked on all fours, had a short tail and a large head with a hooked beak. It had a bony neck-frill at the rear of the skull, which sported a pair of long spikes, which curved towards the outside. Adult Achelousaurus had rough bosses (roundish protuberances) above the eyes and on the snout where other centrosaurines often had horns in the same positions. These bosses were covered by a thick layer of keratin, but their exact shape in life is uncertain. Some researchers hypothesize that the bosses were used in fights, with the animals butting each other's heads, as well as for display.$$,
    'https://brunosouzadev-dinoapi.s3.sa-east-1.amazonaws.com/images/achelousaurus.jpg',
    3,
    5,
    200.0,
    true
)